### ISSUE TITLE
Feature Req: Add support for separate template files

### ISSUE THREAD

**Issue by jpheintz** [natewallace/angular2-inline#17]
This works great for the html and css inline when setting up a component.  But if the html is specified in another file and imported in, this plugin does not have any affect on the template file.

------------------------------------------------------
// foo.component.ts
import {FooComponentTemplate} from './foo.component.html';
@Component({
  selector: 'foo',
  template: FooComponentTemplate
})
------------------------------------------------------
// foo.component.html.ts
export const FooComponentTempalte = `
  <div>
    . . . . 
  </div>
`;

**Comment by natewallace** [comment]
If you are going to put your html in another file you should probably just use the **templateUrl** property instead of **template**.  For example:

foo.component.html:
```html
<div>stuff</div>
```

foo.component.ts:
```js
@Component({
  selector: 'foo'
  templateUrl: './foo.component.html'
})
```

If this doesn't work for you then you will need to create a literal object with a template property in order to get this extension to highlight it.  For example:

foo.component.html:
```js
const foo = {
  template: `<div>stuff</div>`
};
export const FooComponentTemplate = foo.template;
```
